version: '3.8'

services:
  test-project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-project
    ports:
      - "8088:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - test-project-network
    environment:
      - PROJECT_NAME=test-project
      - DOMAIN_NAME=test-project.local

networks:
  test-project-network:
    driver: bridge
