version: '3.8'

services:
  test-deploy:
    # Development-specific overrides
    volumes:
      # Add volume for live reloading
      - ./html:/usr/share/nginx/html:ro
      # Mount custom development configuration
      - ./conf.d/dev:/etc/nginx/conf.d/dev:ro
    environment:
      # Development environment variables
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - ENVIRONMENT=development
    # Enable development ports
    ports:
      - "8081:80"
    # Development-specific healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    # Development-specific restart policy
    restart: unless-stopped
    # Add development labels
    labels:
      - "dev.environment=true"
      - "dev.project=test-deploy"

networks:
  test-deploy-network:
    driver: bridge
    # Development-specific network configuration
    ipam:
      config:
        - subnet: 172.28.213.0/24

- hosts:
    - "test-debug.local"
    - "second-app.local"
    - "mapakms.com"
    - "fresh-test.local"
  # Cloudflare integration disabled for now
  # cf_token: "YOUR_CLOUDFLARE_API_TOKEN"
  # cf_account_id: "YOUR_CLOUDFLARE_ACCOUNT_ID"
  # cf_zone_id: "YOUR_CLOUDFLARE_ZONE_ID" 